import { AccountType } from '../account';
import { IAccount, IAttributes as IMoneyTransferActionAttributes } from '../action/transfer/moneyTransfer';
import { IExtendId } from '../autoGenerated';
import { IClientUser } from '../clientUser';
import * as TransactionFactory from '../transaction';
import TransactionType from '../transactionType';

export type IRecipient = TransactionFactory.IRecipient;
export type IAgent = TransactionFactory.IAgent;

/**
 * 取引開始パラメーターインターフェース
 */
export type IStartParams<T extends AccountType> = TransactionFactory.IStartParams<TransactionType.Transfer, IAgent, IRecipient, IObject<T>>;

export type IResult = any;

/**
 * エラーインターフェース
 */
export type IError = any;

/**
 * 取引対象物インターフェース
 */
export interface IObject<T extends AccountType> {
    clientUser?: IClientUser;
    /**
     * 金額
     */
    amount: number;
    /**
     * 転送元
     */
    fromLocation: IAccount<T>;
    /**
     * 転送先
     */
    toLocation: IAccount<T>;
    description?: string;
}

export interface IPotentialActions<T extends AccountType> {
    moneyTransfer: IMoneyTransferActionAttributes<T>;
}

export type ITransaction<T extends AccountType> = IExtendId<IAttributes<T>>;

/**
 * 転送取引インターフェース
 */
export interface IAttributes<T extends AccountType>
    extends TransactionFactory.IAttributes<IStartParams<T>, IResult, IError, IPotentialActions<T>> {
}
