/**
 * 現金転送中止タスクファクトリー
 */
import TransactionType from '../account/transactionType';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export interface IData {
    transaction: {
        typeOf: TransactionType;
        id: string;
        transactionNumber?: string;
    };
}

export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.CancelAccountMoneyTransfer;
    data: IData;
}

export type ITask = IExtendId<IAttributes>;
