/**
 * 現金転送タスクファクトリー
 */
import { AccountType } from '../account';
import { IAttributes as IMoneyTransferActionAttributes } from '../action/transfer/moneyTransfer';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export interface IData<T extends AccountType> {
    actionAttributes: IMoneyTransferActionAttributes<T>;
}

export interface IAttributes<T extends AccountType> extends TaskFactory.IAttributes {
    name: TaskName.MoneyTransfer;
    data: IData<T>;
}

export type ITask<T extends AccountType> = IExtendId<IAttributes<T>>;
