/**
 * 通貨転送返金タスクファクトリー
 */
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';
import TransactionType from '../transactionType';

export interface IData {
    identifier?: string;
    purpose: {
        typeOf: TransactionType;
        id: string;
        transactionNumber?: string;
    };
}

export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.ReturnMoneyTransfer;
    data: IData;
}

export type ITask = IExtendId<IAttributes>;
