/**
 * タスク実行結果ファクトリー
 * @namespace taskExecutionResult
 */
import { IExtendId } from './autoGenerated';

export interface IAttributes {
    executedAt: Date;
    error: string;
}

export type ITaskExecutionResult = IExtendId<IAttributes>;
